### ISSUE TITLE
add slides about documentation?

### ISSUE THREAD

**Issue by Lotterleben** [ferrous-systems/teaching-material#31]
This was requested in today's training.
they could cover (briefly!):

- `///` vs. `//!`
- hint: you can use markdown in your comments
- running `cargo doc` and looking at the generated html
     - how to *navigate* the created docs: side bar on the left; expanding function docs
     - caution: library docs only cover public members
     - hint: cargo doc will also generate the docs for my project's entire dependency tree
- cross-documentation links
- ✨doctests✨
     - 💡 this can be segwayed into by showing off ` ```rust` formatted example code first; *then* run `cargo test` and tadaaaaah
     - -> effect: our examples can't accidentally fall out sync! and they're 2-in-1 unit tests 
- maybe add a link to https://doc.rust-lang.org/beta/rust-by-example/meta/doc.html and tell people to pay attention to the extra sources at the bottom
- `mdbook`s
    - The Rust Book
    - mention: when Rustaceans refer to a book, they mean a `mdbook` 
    - bigger libraries will publish books for conceptual explanation (like the embedded book, the async book, the rtic book...)

assigning @jamesmunns because he was giving the training and mentioned he'd like slides – not sure who's available to write these at the moment

**Comment by skade** [comment]
https://github.com/ferrous-systems/teaching-material/tree/master/presentations/documentation it seems like those slides weren't linked in the overview.

**Comment by Lotterleben** [comment]
ah! thank you! (also– Florian, you're on vacation, get outta here ☝️)
