### ISSUE TITLE
Control Flow: simplify option/result example

### ISSUE THREAD

**Issue by Lotterleben** [ferrous-systems/teaching-material#71]
the [current example for "Using Option and Result"](https://ferrous-systems.github.io/teaching-material/control-flow.html#/_using_option_and_result) shows unidiomatic code (you can just loop over the vec without an iterator?) and easily sends you down a rabbit hole of consuming functions, iterators, mutability etc. It should be swapped out for a simpler example

**Comment by spookyvision** [comment]
I vote for
- [checked_add](https://doc.rust-lang.org/std/primitive.i32.html#method.checked_add) to showcase `Option` usage
- extending the iterator deck by some slides that explain the "emit `Some(t)` until exhausted, then emit `None` machinery and the implicit call of `into_iter()` caused by `for`

**Comment by Lotterleben** [comment]
sounds good!
